title: Kenny Tran
logo: assets/1753811203677.jfif
description: IT Audit & Compliance | Cybersecurity | SOX Compliance | AI Governance | CompTIA A+ Certified | Computer Information Systems Student | Aspiring CISA & CIA
#show_downloads: true
theme: jekyll-theme-minimal
