title: Kenny Tran
logo: headshot.png
description: Computer Information Systems and Technology Student | CompTIA A+ Certified | Cybersecurity & IT Audit Enthusiast
#show_downloads: true
theme: jekyll-theme-minimal
