title: Kenny Tran
logo: ![image alt](https://github.com/kennytran10/portfolio/blob/b6fb96a3fc2b8fdf7b63ac4c6096604c93d38b4d/assets/1726500858498.jpg)
description: Computer Information Systems and Technology Student | CompTIA A+ Certified | Cybersecurity & IT Audit Enthusiast
#show_downloads: true
theme: jekyll-theme-minimal
